CRITICAL - 2020-10-10 05:07:28 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:07:44 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:07:53 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:09:02 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:11:26 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:11:41 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:12:04 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:12:05 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:17:57 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:17:58 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:18:35 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:18:35 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:26:49 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:26:50 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:30:04 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:30:04 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:30:11 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:30:11 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:30:18 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1952): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(52): CodeIgniter\Database\BaseBuilder->countAllResults()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(29): App\Models\AbsensiModel->checkAbsensiHariIni()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->checkAbsen()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:30:18 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:30:23 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1952): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(52): CodeIgniter\Database\BaseBuilder->countAllResults()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(29): App\Models\AbsensiModel->checkAbsensiHariIni()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->checkAbsen()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:30:23 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:30:41 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:30:41 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:30:56 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:31:30 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:31:30 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:31:36 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:31:37 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 05:32:14 --> Unable to connect to the database.
#0 C:\xampp\htdocs\tpq\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tpq\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `id_ust`...', Array, false)
#2 C:\xampp\htdocs\tpq\app\Models\AbsensiModel.php(31): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tpq\app\Controllers\Home.php(19): App\Models\AbsensiModel->getAbsensi()
#4 C:\xampp\htdocs\tpq\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\xampp\htdocs\tpq\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-10-10 05:32:15 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\tpq\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(308): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tpq\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-10-10 18:42:18 --> syntax error, unexpected 'Print' (T_PRINT), expecting identifier (T_STRING)
#0 C:\xampp\htdocs\tpq\system\Router\Router.php(195): CodeIgniter\Router\Router->autoRoute('print')
#1 C:\xampp\htdocs\tpq\system\CodeIgniter.php(793): CodeIgniter\Router\Router->handle('print')
#2 C:\xampp\htdocs\tpq\system\CodeIgniter.php(364): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-10-10 18:42:39 --> syntax error, unexpected 'Print' (T_PRINT), expecting identifier (T_STRING)
#0 C:\xampp\htdocs\tpq\system\Router\Router.php(195): CodeIgniter\Router\Router->autoRoute('print')
#1 C:\xampp\htdocs\tpq\system\CodeIgniter.php(793): CodeIgniter\Router\Router->handle('print')
#2 C:\xampp\htdocs\tpq\system\CodeIgniter.php(364): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\tpq\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\tpq\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\tpq\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
